### ISSUE TITLE
Placeholder '@' in application.yaml

### ISSUE THREAD

**Issue by thlaegler** [spring-projects/spring-ide#167]
I'm using maven resource plugin to replace some values in my application.yaml. While the @-character is not allowed as beginning of a yaml token there is this workaround to wrap the value in " or ' ( [here](https://jira.spring.io/browse/STS-4201) and [here](https://jira.spring.io/browse/STS-4250) ).
But is there a similar workaround for integer values like server.port?

```yaml
myproject:
  version: '@project.version@'
  description: '@project.description@'
  java:
    version: '@java.version@'
server:
  port: @xmd.spring.config.port@
```
